config/routes.rb
Rails.application.routes.draw do
  root to: 'game#top'
  get '/results/:id', to: 'results#show'
  post '/results/create', to: 'results#create'
  get '/sessions/new', to: 'sessions#new'
  get '/play', to: 'game#play'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/ranking/show', to: 'ranking#show'
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :results, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include GameHelper
  include ResultsHelper
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def top
    if logged_in?
      @user = current_user
    end
  end

  def play
  end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController
  def show
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  require 'securerandom'

  def create
    @result = Result.new(result_params)
    @result.user = current_user if current_user
    title_info = get_title_info(@result)
    @result.title = title_info[:name]
    @result.uid = SecureRandom.uuid
    if @result.save!
      render json: { status: 200, result_id: @result.id }
    else
      redirect_to root_url
    end
  end

  def show
    @result = Result.find(params[:id])
    title_info = get_title_info(@result)
    @image_path = title_info[:image_path]
    @character_words = title_info[:character_words]
  end

  private
    
    def result_params
      params.require(:result).permit(:tanni_point, :love_point, :club_point, :business_point)
    end

    def get_title_info(result)
      title_list = title_list()
      point_type_list = ["tanni", "love", "business", "club"]
      point_type_list.each do |type|
        delete_title_list = []
        title_list.each do |title|
          unless result[type+"_point"]>=title[(type+"_range").to_sym][0] && result[type+"_point"]<=title[(type+"_range").to_sym][1] then
            delete_title_list.push title
          end
        end
        title_list.delete_if do |title|
          delete_title_list.include?(title)
        end
      end
      if title_list.length == 0 then
        return "マッチしませんでした"
      elsif title_list.length == 1 then
        return title_list[0]
      elsif title_list.length >= 1 then
        return title_list
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @result_uid = params[:result_uid]
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user

      link_user_and_result(user, params[:session][:result_uid]) if params[:session][:result_uid].present?

      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @result_uid = params[:result_uid]
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      log_in @user

      link_user_and_result(@user, params[:user][:result_uid]) if params[:user][:result_uid].present?

      redirect_to @user
    else
      reder 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @title_list = title_list()
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
  def title_list
    infinite = 1000000000
    title_list = [
      {
        name: "留年",
        tanni_range:    [0, 123],
        love_range:     [1, 99],
        business_range: [0, infinite],
        club_range:     [0, infinite],
        image_path: "retention.png",
        character_words: "もう一年遊べるわぁ",
      },
      {
        name: "ニート",
        tanni_range:    [0, 123],
        love_range:     [0, 0],
        business_range: [0, infinite],
        club_range:     [0, infinite],
        image_path: "neet.png",
        character_words: "有産階級の仲間入りですわwww",
      },
      {
        name: "ヒモ",
        tanni_range:    [0, 123],
        love_range:     [100, infinite],
        business_range: [0, 49],
        club_range:     [0, infinite],
        image_path: "himo.png",
        character_words: "俺と付き合えるとか幸せだよなあ。",
      },
      {
        name: "就職浪人",
        tanni_range:    [0, 123],
        love_range:     [100, infinite],
        business_range: [50, infinite],
        club_range:     [0, infinite],
        image_path: "ronin.png",
        character_words: "彼女のためにも良い会社に入るぞ！！！",
      },
      {
        name: "サラリーマン",
        tanni_range:    [124, infinite],
        love_range:     [0, infinite],
        business_range: [0, 99],
        club_range:     [0, infinite],
        image_path: "businessman.png",
        character_words: "宝くじでも買おうかな",
      },
      {
        name: "一流サラリーマン",
        tanni_range:    [124, infinite],
        love_range:     [0, infinite],
        business_range: [100, infinite],
        club_range:     [0, infinite],
        image_path: "businessman_macho.png",
        character_words: "お前らとはレベルが違うんだよなあwww",
      },
      # {
      #   name: "一流サラリーマン",
      #   tanni_range:    [124, infinite],
      #   love_range:     [0, 99],
      #   business_range: [100, infinite],
      #   club_range:     [100, infinite],
      # },
      # {
      #   name: "サラリーマン",
      #   tanni_range:    [124, infinite],
      #   love_range:     [0, 99],
      #   business_range: [50, 99],
      #   club_range:     [0, infinite],
      # },
      # {
      #   name: "フリーター",
      #   tanni_range:    [124, infinite],
      #   love_range:     [0, 100],
      #   business_range: [0, 49],
      #   club_range:     [0, infinite],
      # },
      # {
      #   name: "大学院生",
      #   tanni_range:    [124, infinite],
      #   love_range:     [0, 20],
      #   business_range: [0, 20],
      #   club_range:     [0, infinite],
      # }
    ]
  end
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/results_helper.rb
module ResultsHelper
  def link_user_and_result(user, result_uid)
    result = Result.find_by(uid: result_uid)
    if result
      result.update(user_id: user.id)
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?  
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/game/play.html.haml
= react_component("PlayScreen")

app/views/game/top.html.haml
%div.top-content-wrapper
  %div.buttons-above-title-wrapper
    = button_to "ランキング", "/ranking/show", method: :get, class: "buttons-above-title"
    - if logged_in?
      = button_to "マイページ", @user, method: :get, class: "buttons-above-title"
    - else
      = button_to "新規登録", "/users/new", method: :get, class: "buttons-above-title"
      = button_to "ログイン", "/sessions/new", method: :get, class: "buttons-above-title"
  %div.title 単位落とすな
  = button_to "スタート", "/play", method: :get, class: "start-button"
  = button_to "遊び方", "/play", method: :get, class: "how-to-button"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TanniOtosuna
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
    %br
    = debug(params) if Rails.env.development?

app/views/ranking/show.html.haml
%h1 ランキング

%br

= button_to "トップへ戻る", "/", method: :get

app/views/results/show.html.haml
%h1 This is show page of result!

= react_component("PointGauge", { type: "tanni", point: @result.tanni_point})
= react_component("PointGauge", { type: "love", point: @result.love_point})
= react_component("PointGauge", { type: "business", point: @result.business_point})
= react_component("PointGauge", { type: "club", point: @result.club_point})
%div.buttons-above-title-wrapper
  - unless logged_in?
    = button_to "新規登録", new_user_path, { method: :get, params: {result_uid: @result.uid} }
    %span または
    = button_to "ログイン", sessions_new_path, { method: :get, params: {result_uid: @result.uid} }
    %span してこの結果を保存しましょう！
%h2
  = @result.title
%br
%div
  = @character_words
%div
  = image_tag @image_path, size: '320'

= button_to "トップへ戻る", "/", method: :get

app/views/users/new.html.haml
%h1 Users#new
%p Find me in app/views/users/new.html.erb

= form_for(@user) do |f|
  = f.label :name
  = f.text_field :name

  = f.label :email
  = f.text_field :email

  = f.label :password
  = f.password_field :password

  = f.label :password_confirmation, "Confirmation" 
  = f.password_field :password_confirmation

  = f.hidden_field :result_uid, value: @result_uid

  = f.submit "新規登録", class: "btn btn-primary"

%br
= button_to "トップへ戻る", "/", method: :get

app/views/users/show.html.haml
%h1 this is show page
- if @user
  %div 
    = @user.name
  %div 
    = @user.email
  %br
  = button_to "トップへ戻る", "/", method: :get
  = button_to "ログアウトする", "/logout", method: :delete

- @title_list.each do |t|
  = react_component("TitleDetail", { title: t, count: @user.results.find_all {|r| r.title == t[:name]}.length})